@echo off

if "%1"=="-en" goto english
if "%1"=="-cn" goto chinesesimplified
color 0c
echo 出现错误：此文件为羊牌 UUP 下载向导的专用语言文件。
pause>nul
exit /b

:english
set "langchoose=Choose Wizard Language"
set "langwelcome=Welcome, Choose your language"
set "lang1=English"
set "lang2=Chinese Simplified"
set "dlangtxt=Choose your language and Press Enter to Continue:"

set "line===================================================================================================================="
set "line2=-------------------------------------------------------------------------------------------------------------------"
set "title=JRJSheep UUP Download Wizard"
set "PurposeA=Download Only"
set "PurposeB=Download & Convert"
set "SelectLang=Select Language"
set "SelectSKU=Select the SKU Edition"
set "SelectSKUGroup=Select the SKU Editions Group"
set "UnsupportedSKU=Unsupported SKU Edition"
set "UnsupportedLang=Unsupported Language"
set "WriteBuildID=Fill in the update ID of the downloaded version"
set "SelectTeamID=Choose the Team Edition update ID"
set "SearchUpdScript=Retrieving updated script"
set "DLUUPFiles=Download the UUP files"
set "FoundError=ERROR"

set "WelcomeTitle=               Welcome to download UUP files, please choose network preset for UUP download first"
set "WelDes=The settings on this page are used to control whether to enable revocation server detection. Selecting "Default"  & echo will enable revocation server detection; Select "Alternate" will disable revocation server detection."
set "Def=Default"
set "Alter=Alternate"
set "WizInfo=About The Wizard tool:"
set "WizVer=Version"
set "Build=Build"
set "LangVer=Wizard Language File Version:"

set "CopyRight=JRJSheep Script Localization. All Rights Reserved."
set "VerDes=The development of this tool is inseparable from the support of uupdump ^(whatever127^) and aboddi1406 scripts."

set "TxtDes1=Enter your option and press "Enter":"

set "LangTitle=                                 Select the language used by UUP OS Build"
set "LangDes=Choose the language version of your operating system on this page. Valid range: Home, Home China, Professional, Team. & echo This program only supports Team Edition of version 2004 and above."
set "ListLang=Available Languages List:"
set "LangMenu01=    01 - Arabic [Saudi Arabia]           ^|     20 - Portuguese    [Portugal]"
set "LangMenu02=    02 - Estonian    [Estonia]           ^|     21 - Japanese         [Japan]"
set "LangMenu03=    03 - Bulgarian  [Bulgaria]           ^|     22 - Swedish         [Sweden]"
set "LangMenu04=    04 - Polish       [Poland]           ^|     23 - Serbian-Latin   [Serbia]"
set "LangMenu05=    05 - Korean        [Korea]           ^|     24 - Slovak          [Slovak]"
set "LangMenu06=    06 - Danish      [Denmark]           ^|     25 - Slovenian     [Slovenia]"
set "LangMenu07=    07 - German      [Germany]           ^|     26 - Thai          [Thailand]"
set "LangMenu08=    08 - Russian      [Russia]           ^|     27 - Turkish         [Turkey]"
set "LangMenu09=    09 - Finnish     [Finland]           ^|     28 - Ukrainian       [Ukrain]"
set "LangMenu10=    10 - French       [France]           ^|     29 - Spanish         [Mexico]"
set "LangMenu11=    11 - French       [Canada]           ^|     30 - Spanish          [Spain]"
set "LangMenu12=    12 - Dutch   [Netherlands]           ^|     31 - Greek           [Greece]"
set "LangMenu13=    13 - Czech[Czech Republic]           ^|     32 - Hebrew          [Israel]"
set "LangMenu14=    14 - Croatian    [Croatia]           ^|     33 - Hungarian     [Hungaria]"
set "LangMenu15=    15 - Latvian      [Latvia]           ^|     34 - English  [United States]"
set "LangMenu16=    16 - Lithuanian[Lithuania]           ^|     35 - English [United Kingdom]"
set "LangMenu17=    17 - Romanian    [Romania]           ^|     36 - Italian          [Italy]"
set "LangMenu18=    18 - Norwegian    [Bokmal]           ^|     37 - Chinese     [Simplified]"
set "LangMenu19=    19 - Portuguese   [Brazil]           ^|     38 - Chinese    [Traditional]"

set "BuildTitle=                             Select the Build which you want to download via UUP"
set "BuildDes1=This page will select a certain SKU Edition which you download via UUP. For Team Edition, it will automatically go to the corresponding menu to select the & echo Build after selection; if you want to download the combined version of the UUP files, select "download combined Build". & echo Note: If you need other versions such as ProfessionalWorkstation, Enterprise, etc., select "Pro"."
set "COBuild=Core"
set "CCSBuild=Core Country Specific"
set "ProBuild=Pro"
set "TeamBuild=Team ^(Build 19041.350 and above^)"
set "CombBuild=Download combined Build"

set "EditionTitle=                           Select a combination SKU which you want to download via UUP"
set "EditionDes1=The content of this page is to select the combined SKU Build that will be downloaded via UUP.  & echo After you select and press "Enter" to confirm, the download will start immediately."
set "CCCS=Core and Core Country Specific"
set "CAPR=Core and Pro"
set "CCSP=Core Country Specific and Pro"
set "CCCSP=Core, Core Country Specific and Pro"

set "WarTitle=                                               W A R N I N G"
set "Wartxt=The single Edition or Combined Edition number you entered is invalid. It does not refer to any single Edition or & echo combined Edition provided, please select again."
set "SingleEdt=Return to Select Single Edition Menu"
set "CombEdt=Return to Select combined Edition Menu"
set "Exit=Exit the Wizard Script"
set "ContExit=Please enter your option and press "Enter" to return, or just press "Enter" to exit:"
set "CodError=The language code you entered is invalid. It does not refer to any language version provided in the menu, & echo re-select in the language menu."

set "BackLangMenu=Return to Select language Version Menu"

set "FillIDTitle=                        Fill in the update ID of the Build you want to download"
set "FillIDDes=Fill in the update ID of the Build to be downloaded on this page. Paste input is supported.& echo Note: The update ID corresponding to each internal version and each architecture version is different. Therefore, you & echo neither need to specifically set which architecture version to download, nor paste the corresponding update name."
set "IDExample=Update ID Example: "
set "FillID=Fill in the Update ID: "

set "TeamTitle=                         Team Edition, version 2004 and above - Update ID selection"
set "TeamDes=This page selects the collaborative version of UUP file download. The collaborative version is an unconventional & echo version, you don’t need to fill in the update ID, just select the version from the menu to start downloading."
set "Team20H2=The following Builds are Team Edition, Version 20H2: "
set "TeamBranch=and related branches"

set "UPDScript=Retrieving updated aria2 script..."
set "DLFiles=Attempting to download files..."

set "ErrorTitle=                                               E R R O R"
set "ErrorTxt1=We could not find %aria2% in the current directory. Therefore, the download cannot continue."
set "DLAria=You can download aria2 from:"
set "ErrorTxt2=After downloading, Extract the files in the aria2 compressed package to the following path to download normally:"
set "FileExample=Current folder：%~dp0"
set "ErrorTxt3=Sorry, an error occurred while downloading the file."
set "ErrorTxt4=If you want to continue to fill in the files that have not been downloaded, please run this script again after exiting."
set "ErrorTxt5=Unable to retrieve data from Windows Update servers. Reason: "
set "ErrorTxt6=If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers."
set "ErrorTxt7=It is recommended that you change to a valid update ID."
exit /b

:chinesesimplified
set "langchoose=请选择向导语言"
set "langwelcome=欢迎使用，请选择你的语言"
set "lang1=英    语"
set "lang2=简体中文"
set "dlangtxt=请选择你语言，并按 Enter 键继续："

set "line================================================================================="
set "line2=--------------------------------------------------------------------------------"
set "title=羊牌 UUP 下载向导"
set "PurposeA=仅下载"
set "PurposeB=下载并转制"
set "SelectLang=选择语言"
set "SelectSKU=选择 SKU 版本"
set "SelectSKUGroup=选择 SKU 版本组合"
set "UnsupportedSKU=不支持的 SKU 版本"
set "UnsupportedLang=不支持的语言"
set "WriteBuildID=填写下载版本的更新 ID"
set "SelectTeamID=选择协同版更新 ID"
set "SearchUpdScript=检索更新脚本"
set "DLUUPFiles=下载 UUP 文件"
set "FoundError=出现错误"

set "WelcomeTitle=                 欢迎下载 UUP 文件，请选择 UUP 下载网络预先设置"
set "WelDes=此页设置用于控制是否启用吊销服务器检测。选择“默认”将会启用吊销服务器检测；选择 & echo “备用”将会禁用吊销服务器检测。"
set "Def=默认"
set "Alter=备用"
set "WizInfo=关于此向导工具："
set "WizVer=版本"
set "Build=内部版本"
set "LangVer=向导语言文件版本："
set "CopyRight=正义羊脚本汉化。保留所有权利。"
set "VerDes=此工具的开发离不开 uupdump ^(whatever127^) 和 aboddi1406 脚本的支持。"

set "TxtDes1=请输入你的选项代码并按“Enter”键："

set "LangTitle=                          请选择 UUP 版本使用的语言"
set "LangDes=本页选择你使用的操作系统语言版本。有效范围：家庭版、家庭中文版、专业版、协同版。& echo 本程序仅支持版本 2004 及以上版本的协同版。"
set "ListLang=可用的语言列表："
set "LangMenu01=    01 - 阿拉伯语 [沙特阿拉伯]          ^|     20 - 葡萄牙语        [葡萄牙]"
set "LangMenu02=    02 - 爱沙尼亚语 [爱沙尼亚]          ^|     21 - 日语              [日本]"
set "LangMenu03=    03 - 保加利亚语 [保加利亚]          ^|     22 - 瑞典语            [瑞典]"
set "LangMenu04=    04 - 波兰语         [波兰]          ^|     23 - 塞尔维亚语    [塞尔维亚]"
set "LangMenu05=    05 - 朝鲜语         [韩国]          ^|     24 - 斯洛伐克语    [斯洛伐克]"
set "LangMenu06=    06 - 丹麦语         [丹麦]          ^|     25 - 斯洛文尼亚语[斯洛文尼亚]"
set "LangMenu07=    07 - 德语           [德国]          ^|     26 - 泰语              [泰国]"
set "LangMenu08=    08 - 俄语         [俄罗斯]          ^|     27 - 土耳其语        [土耳其]"
set "LangMenu09=    09 - 芬兰语         [芬兰]          ^|     28 - 乌克兰语        [乌克兰]"
set "LangMenu10=    10 - 法语           [法国]          ^|     29 - 西班牙语        [墨西哥]"
set "LangMenu11=    11 - 法语         [加拿大]          ^|     30 - 西班牙语        [西班牙]"
set "LangMenu12=    12 - 荷兰语         [荷兰]          ^|     31 - 希腊语            [希腊]"
set "LangMenu13=    13 - 捷克语   [捷克共和国]          ^|     32 - 希伯来语        [以色列]"
set "LangMenu14=    14 - 克罗地亚语 [克罗地亚]          ^|     33 - 匈牙利语        [匈牙利]"
set "LangMenu15=    15 - 拉脱维亚语 [拉脱维亚]          ^|     34 - 英语              [美国]"
set "LangMenu16=    16 - 立陶宛语     [立陶宛]          ^|     35 - 英语              [英国]"
set "LangMenu17=    17 - 罗马尼亚语 [罗马尼亚]          ^|     36 - 意大利语        [意大利]"
set "LangMenu18=    18 - 挪威语         [挪威]          ^|     37 - 中文              [简体]"
set "LangMenu19=    19 - 葡萄牙语       [巴西]          ^|     38 - 中文              [繁体]"

set "BuildTitle=                       请选择你要通过 UUP 下载的内部版本"
set "BuildDes=此页选择通过 UUP 下载的某一 SKU 版本。对于协同版，将会在选择后自动转到对应菜单进 & echo 行版本的选择；如果你要下载组合版本的 UUP 文件，请选择“下载组合版本”。 & echo 注：如果你需要形如专业工作站版、企业版等其他版本，请选择“专业版”。"
set "COBuild=家庭版"
set "CCSBuild=家庭中文版"
set "ProBuild=专业版"
set "TeamBuild=协同版 ^(Build 19041.350 及以上^)"
set "CombBuild=下载组合版本"

set "EditionTitle=                           请选择组合 SKU 版本下载"
set "EditionDes=此页内容是选择通过 UUP 下载的组合 SKU 版本。在你选择并按“Enter”键确认后，将会 & echo 立即开始下载。"
set "CCCS=家庭版和家庭中文版"
set "CAPR=家庭版和专业版"
set "CCSP=家庭中文版和专业版"
set "CCCSP=家庭版、家庭中文版和专业版"

set "WarTitle=                                  警    告"
set "Wartxt=你所输入的单一版本或组合版本的编号是无效的。其不指代提供的任何单一版本或组合版 & echo 本，请重新进行选择。"
set "SingleEdt=返回到选择单一版本菜单"
set "CombEdt=返回到选择组合版本菜单"
set "Exit=退出向导脚本"
set "ContExit=请输入你的选项代码，并按“Enter”键返回，或直接按“Enter”键退出："
set "CodError=你所输入的语言代码是无效的。其不指代菜单中所提供的任何一个语言版本，请重新在语 & echo 言菜单中进行选择。"

set "BackLangMenu=返回到选择语言版本菜单"

set "FillIDTitle=                        填写你要下载的版本使用的更新 ID"
set "FillIDDes=此页填写要下载版本的更新 ID，支持粘贴输入。 & echo 注：每一个内部版本及各体系结构版本对应的更新 ID 是不同的。因此你既不需要专门设置 & echo 下载何种体系结构的版本，也不需要粘贴对应的更新名称。"
set "IDExample=更新 ID 示例："
set "FillID=请填写更新 ID："

set "TeamTitle=                   协同版，版本 2004 及以上——更新 ID 选择"
set "TeamDes=此页选择协同版的 UUP 文件下载。协同版非常规版本，你不需要填写更新 ID，仅需从菜单 & echo 中选择版本即可开始下载。"
set "Team20H2=以下是协同版，版本 20H2："
set "TeamBranch=和相关分支"

set "UPDScript=正在检索更新的 aria2 脚本……"
set "DLFiles=正在尝试下载文件……"
set "PrepConverter=正在解压 UUP 转换程序……"

set "ErrorTitle=                                 出 现 错 误"
set "ErrorTxt1=我们无法在当前的目录中找到 %aria2%。因此下载无法继续。"
set "DLAria=你可以在此处下载 aria2："
set "ErrorTxt2=下载后，将 aria2 压缩包中的文件解压到以下路径，即可正常进行下载："
set "FileExample=当前文件夹：%~dp0"
set "ErrorTxt3=很抱歉，在下载文件时出现错误。"
set "ErrorTxt4=如果你希望继续补齐未能下载完成的文件，请在退出后再次运行此脚本。"
set "ErrorTxt5=无法从 Windows 更新服务器检索数据。原因："
set "ErrorTxt6=如果此问题仍持续存在，很有可能是你所尝试下载的 UUP 集已从 Windows 更新服务器中删除。"
set "ErrorTxt7=建议你更换一个有效更新 ID。"
set "ErrorTxt8=我们无法找到此脚本所需的文件。"
set "ErrorTxt9=如果你希望补充缺失的文件，可以在补充文件后再次执行。"
exit /b